// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtfNkFb8T_DBUt75vqPfUKJoOtqHdfpbM',
    appId: '1:699351213389:web:e55dc5f576bad5ab520304',
    messagingSenderId: '699351213389',
    projectId: 'mazeandtraps',
    authDomain: 'mazeandtraps.firebaseapp.com',
    storageBucket: 'mazeandtraps.appspot.com',
    measurementId: 'G-1T5LJ3GNPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgT7Ga_Rmoq0Ul2KuqE4scxq46pKjxynY',
    appId: '1:699351213389:android:f48d7532c60d74da520304',
    messagingSenderId: '699351213389',
    projectId: 'mazeandtraps',
    storageBucket: 'mazeandtraps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ZmP4f5AGZqO_2BEOnl3CSVID0prZXu8',
    appId: '1:699351213389:ios:185c75f82a973cb2520304',
    messagingSenderId: '699351213389',
    projectId: 'mazeandtraps',
    storageBucket: 'mazeandtraps.appspot.com',
    iosBundleId: 'com.example.mazeandtraps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3ZmP4f5AGZqO_2BEOnl3CSVID0prZXu8',
    appId: '1:699351213389:ios:185c75f82a973cb2520304',
    messagingSenderId: '699351213389',
    projectId: 'mazeandtraps',
    storageBucket: 'mazeandtraps.appspot.com',
    iosBundleId: 'com.example.mazeandtraps',
  );
}
